services:
  postgres:
    image: postgres:15
    container_name: postgres_api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batata
      POSTGRES_DB: db_api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
